name: Android CI/CD

on:
  push:
    branches:
      - main  # или другая ветка, на которой вы хотите запускать CI/CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and test
      run: |
        ./gradlew build
        ./gradlew test

    # Добавьте дополнительные шаги по необходимости
