name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        run: |
          sudo apt-get install -y openjdk-17-jdk
          echo "##[set-output name=javaHome]$(which java)"
        id: java
        continue-on-error: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: |
          ./gradlew check
          ./gradlew test

      - name: Package APK
        run: ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-bundle
          path: app/build/outputs/bundle/release/app-release.aab
